name: Deploy to Vercel (Release)

on:
  push:
    branches:
      - release/v1.0.0-beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}